### ISSUE TITLE
Repo mangler initialt indhold

### ISSUE THREAD

**Issue by Mat-Gr** [CodingPirates/PiratSkibet#1]
Man kan ikke oprette en fork/lave pull-requests på et tomt repo.

Har I muligheden for at oprette en "main" branch og lave et "initial commit"?

**Comment by Rotendahl** [comment]
Det er der nu @Mat-Gr så du burde kunne lave en pr nu

**Comment by Mat-Gr** [comment]
Den er umiddelbart stadig tom for mig

![github](https://user-images.githubusercontent.com/22744066/104888350-e77cfc00-596c-11eb-80a2-a06fe14a9f90.png)

**Comment by Rotendahl** [comment]
@Mat-Gr det var mig der var en hat og ikke fik pushet det jeg havde committet. Prøv nu
